# Generated by Django 4.1 on 2022-09-03 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.CharField(max_length=250)),
                ('condition', models.TextField(help_text="Patient's condition during treatment")),
                ('recommendations', models.TextField(help_text='Recommendations and medications')),
                ('is_recovered', models.BooleanField()),
            ],
        ),
    ]
